version: '3.7'

services:
  step-ca:
    image: defn/step
    env_file: .env
    command: "${_STEP_CA}"
    volumes:
    - $HOME/.password-store/step:/home/step
  step-cli:
    image: defn/step:cli
    network_mode: service:step-ca
    pid: service:step-ca
    entrypoint: [ "/add-host" ]
    command: "${_STEP_HOST}"
    volumes:
    - $HOME/.password-store/step:/home/step
    - $HOME/.password-store/step/hosts:/data/ssh
    depends_on:
      - step-ca
