#!/bin/bash

trap 'rm -vf /home/step/.step/.pw' EXIT

set -efu

user="$1"; shift

sleep 2

token="$(step ca token ${user} --not-after 11s --ssh --password-file .step/.pw "$@")"
step ssh certificate --token "${token}" -f --insecure --no-password --sign "$@" "${user}" /data/ssh/id_rsa.pub

kill 1
